#!/usr/bin/env python
from pprint import pprint
import src.p4tools as p4tools
from src.p4_files import names
tools = p4tools.P4Tools('//depot/EDW/SQLServer/LZ')
dirs = tools.traverse_top_level_dirs()

